apiVersion: v1
kind: Service
metadata:
  name: drupal-service
  labels:
    app: drupal-service
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
  - name: "30095"
    port: 3095
    protocol: TCP
    nodePort: 30095